### ISSUE TITLE
OdooV12 Error printing report

### ISSUE THREAD

**Issue by croldan87** [JayVora-SerpentCS/Jasperv8#105] opened 2020-02-29 06:53 UTC
Hi, some time ago the module was working but right now I'm having an issue. I'm attaching part of the log when I'm trying to print.

And if you look at this url:
http://jasperreports.sourceforge.net/jasperreports
Gives an error.

[log-odoov12.txt](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/4270004/log-odoov12.txt)

**Comment by JayVora-SerpentCS** [comment] 2020-03-02 07:01
@hiren-serpentcs

**Comment by hiren-serpentcs** [comment] 2020-03-11 06:26
@croldan87 

Thanks for reporting the issue.

Looking at your log file, it seems like the problem is due to the connectivity between Jasper Server and odoo. 

Can you try to print the report by starting the Jasper Server separately?

Thanks

**Comment by hiren-serpentcs** [comment] 2020-08-20 07:13
@JayVora-SerpentCS 

We can assume this is fixed and close the issue.

@croldan87  you can reopen the issue if it's not fixed.

**Closed as completed** 2020-08-21 07:16 UTC
