### ISSUE TITLE
print error:Uncaught TypeError: Cannot read property 'body' of null

### ISSUE THREAD

**Issue by lili94** [JayVora-SerpentCS/Jasperv8#84] opened 2019-04-14 14:37 UTC
hi i am using jasper report in odoo v11 , i create my xml template and desgin it in jasper studio , and i import it in my odoo project when i click in print  button i got these error "Uncaught TypeError: Cannot read property 'body' of null" please help

**Comment by hiren-serpentcs** [comment] 2019-04-15 05:10
Hello @lili94,

Thanks for Reporting Issue.

The issue might be due to the Jasper Server or Jasper report.
Can you please provide us your `.jrml` file as well as the java log file (which is located at `/jasper_reports/java/jasperserver.log` ?

Meanwhile, you can check the detailed configuration in https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation

**Comment by lili94** [comment] 2019-04-15 08:24
hi @hiren-serpentcs  thanks for your replay i follow the documentation exactly like you do, but i got the same error, this is my log and my jrxml file i make it for test
[jasper_devis.txt](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/3079097/jasper_devis.txt)
My log
[jasperserver.txt](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/3079108/jasperserver.txt)

thanks for help please

**Comment by lili94** [comment] 2019-04-15 09:01
@hiren-serpentcs  do you find the isues

**Comment by hiren-serpentcs** [comment] 2019-04-15 10:12
Hello @lili94,
After looking into your log file, the problem is with the Jasper Server connectivity. The Jasper server is trying to connect with a wrong username and password. Can you please check the db username and db password in the odoo configuration?

**Comment by lili94** [comment] 2019-04-15 11:19
hi @hiren-serpentcs  thanks for replay i create new database
db username :cetic_odoo7 
db password :cetic2018 in odoo configuration  and i install jasper and sale module  i fix the error of Uuid when i print your demo i got the same error this is the  my new log 
[jasperserver.txt](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/3079829/jasperserver.txt) i find this file in /jasper_reports/java/ 
[jasperserver.log](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/3079830/jasperserver.log) may help you 
 
thanks sir

**Comment by hiren-serpentcs** [comment] 2019-04-15 11:34
Hello @lili94,
 Looking at the log file, I guess you have accidentally misplaced a quote during the deletion of uuid in the `.jrxml` file.

**Comment by lili94** [comment] 2019-04-15 12:00
hi @hiren-serpentcs  this is my jrxml after delete uuid
[sale_order_report.txt.txt](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/3079946/sale_order_report.txt.txt)
log
[jasperserver.txt](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/3079971/jasperserver.txt)

thanks i need to work so much
[jasperserver.log](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/3079977/jasperserver.log)

**Comment by hiren-serpentcs** [comment] 2019-04-16 05:20
Hi @lili94,
You have to remove the uuid attribute along with it's value as well from your `.jrxml` file.

You can refer to the documentation here: https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation#uuid-error

**Comment by lili94** [comment] 2019-04-16 14:16
hi @hiren-serpentcs  after fixed the problem of uuid i will got this error  help me please
![Capture_test](https://user-images.githubusercontent.com/32308220/56216999-5f144d80-605a-11e9-939a-a63a08d35e0a.PNG)

**Comment by vimalpatelserpentcs** [comment] 2019-04-19 05:40
Hi @lili94,
We have checked your logs and `jrxml` file and also we added your `jrxml` file into the local system, it's working well.
It would be nice to have to add reproduce steps or video/screenshot link so we will to get a better idea about your issue

Thanks & Regards
Vimal Patel

**Comment by ahmedToufikDahmri** [comment] 2019-07-07 13:47
i get this error when trying to print reports

![image](https://user-images.githubusercontent.com/51954376/60769269-e0b1cf80-a0cd-11e9-9ca0-0197ca5cd96b.png)

**Comment by hiren-serpentcs** [comment] 2020-08-20 07:14
@JayVora-SerpentCS 

We can assume this is fixed and close the issue.

@lili94  you can reopen the issue if it's not fixed.

**Closed as completed** 2020-10-09 06:25 UTC
