### ISSUE TITLE
ODOO12 Error: Something happened while trying to contact the server, check that the server is online and that you still have a working network connection.Something happened while trying to contact the server, check that the server is online and that you still have a working network connection.

### ISSUE THREAD

**Issue by nopjeab** [JayVora-SerpentCS/Jasperv8#99] opened 2019-11-12 03:45 UTC
I try generate report jasper but it have error **Something happened while trying to contact the server, check that the server is online and that you still have a working network connection.**

How to fix it?
![screenshot_20191112_105016](https://user-images.githubusercontent.com/48899439/68640182-858b6000-0539-11ea-8a2f-8b6a5ed40a8f.png)

**Comment by JayVora-SerpentCS** [comment] 2019-11-12 06:02
@hiren-serpentcs

**Comment by hiren-serpentcs** [comment] 2019-11-13 13:11
Hello @nopjeab,

Thanks for reporting the issue. 

Can you please share the full server log?

**Comment by nopjeab** [comment] 2019-11-22 07:07
Hello @hiren-serpentcs 

Please log

2019-11-22 07:08:05,328 25642 INFO ? odoo.service.server: Initiating shutdown 
2019-11-22 07:08:05,329 25642 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-11-22 07:08:06,457 26025 INFO ? odoo: Odoo version 12.0 
2019-11-22 07:08:06,458 26025 INFO ? odoo: Using configuration file at /etc/odoo.conf 
2019-11-22 07:08:06,458 26025 INFO ? odoo: addons paths: ['/opt/odoo/.local/share/Odoo/addons/12.0', '/opt/odoo/odoo12/addons', '/opt/odoo/odoo12/odoo/addons'] 
2019-11-22 07:08:06,459 26025 INFO ? odoo: database: odoo@default:default 
2019-11-22 07:08:06,623 26025 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-11-22 07:08:06,859 26025 INFO ? odoo.service.server: HTTP service (werkzeug) running on localhost.localdomain:8069 
2019-11-22 07:08:16,741 26025 INFO ? odoo.http: HTTP Configuring static files 
2019-11-22 07:08:16,791 26025 INFO demo_db odoo.modules.loading: loading 1 modules... 
2019-11-22 07:08:16,849 26025 INFO demo_db odoo.modules.loading: 1 modules loaded in 0.05s, 0 queries 
2019-11-22 07:08:17,039 26025 INFO demo_db odoo.modules.loading: loading 99 modules... 
2019-11-22 07:08:17,655 26025 INFO demo_db odoo.addons.sms.wizard.send_sms: The `phonenumbers` Python module is not available. Phone number validation will be skipped. Try `pip3 install phonenumbers` to install it. 
2019-11-22 07:08:18,418 26025 INFO demo_db odoo.modules.loading: 99 modules loaded in 1.38s, 0 queries 
2019-11-22 07:08:18,801 26025 WARNING demo_db odoo.fields: Field sprogroup.purchase.request.line.product_uom_id with unknown comodel_name 'product.uom' 
2019-11-22 07:08:19,880 26025 INFO demo_db odoo.modules.loading: Modules loaded. 
2019-11-22 07:08:19,892 26025 INFO demo_db odoo.addons.base.models.ir_http: Generating routing map 
2019-11-22 07:08:19,893 26025 INFO demo_db odoo.addons.base.models.ir_http: Generating routing map 
2019-11-22 07:08:20,068 26025 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres 
2019-11-22 07:08:20,118 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:20] "POST /web/action/load HTTP/1.1" 200 - 69 0.108 3.260
2019-11-22 07:08:20,294 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:20] "POST /web/dataset/call_kw/stock.picking.type/load_views HTTP/1.1" 200 - 72 0.052 0.074
2019-11-22 07:08:20,548 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:20] "POST /web/dataset/search_read HTTP/1.1" 200 - 46 0.099 0.067
2019-11-22 07:08:23,901 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:23] "POST /web/action/load HTTP/1.1" 200 - 53 0.054 0.110
2019-11-22 07:08:24,467 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:24] "POST /web/dataset/call_kw/purchase.order/load_views HTTP/1.1" 200 - 145 0.165 0.380
2019-11-22 07:08:24,558 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:24] "POST /web/dataset/search_read HTTP/1.1" 200 - 11 0.015 0.018
2019-11-22 07:08:26,992 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:26] "POST /web/dataset/call_kw/sprogroup.purchase.request/load_views HTTP/1.1" 200 - 64 0.077 0.193
2019-11-22 07:08:27,097 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:27] "POST /web/dataset/call_kw/res.users/name_get HTTP/1.1" 200 - 15 0.021 0.030
2019-11-22 07:08:27,164 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:27] "POST /web/dataset/search_read HTTP/1.1" 200 - 8 0.016 0.017
2019-11-22 07:08:28,395 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:28] "POST /web/dataset/call_kw/sprogroup.purchase.request/read HTTP/1.1" 200 - 21 0.039 0.032
2019-11-22 07:08:28,469 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:28] "POST /web/dataset/call_kw/sprogroup.purchase.request.line/read HTTP/1.1" 200 - 8 0.017 0.023
2019-11-22 07:08:28,616 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:28] "POST /mail/read_followers HTTP/1.1" 200 - 10 0.015 0.022
2019-11-22 07:08:31,029 26025 INFO demo_db werkzeug: 192.168.80.72 - - [22/Nov/2019 07:08:31] "POST /web/action/load HTTP/1.1" 200 - 11 0.012 0.027
2019-11-22 07:08:31,111 26025 INFO demo_db odoo.addons.jasper_reports.JasperReports.jasper_report_config: Requested report: '/opt/odoo/odoo12/addons/jasper_reports/custom_reports/PurRequestXML.jrxml' 
2019-11-22 07:08:31,118 26025 INFO demo_db odoo.addons.jasper_reports.JasperReports.jasper_report_config: Temporary data file: '/tmp/tmpnkye1vwy'

**Comment by hiren-serpentcs** [comment] 2019-12-09 05:29
@nopjeab, Is it the full server log? Because the log is only till the server is creating a temporary data file not after that and if you're running the jasper server explicitly, then can you please share the jasper server log as well.

**Comment by ghost** [comment] 2019-12-13 12:27
Hello @hiren-serpentcs   Same error for me

PFYI

2019-12-13 12:08:16,279 22035 INFO demo1 odoo.addons.jasper_reports.JasperReports.jasper_report_config: Temporary data file: '/tmp/tmpkl9irmft' 
2019-12-13 12:08:17,474 22035 ERROR demo1 odoo.addons.jasper_reports.JasperReports.jasper_server: EXCEPTION: [Errno 111] Connection refused (111, 'Connection refused') 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/nantic/jasperreports/JasperServer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
2019-12-13 12:08:18,476 22035 ERROR demo1 odoo.addons.jasper_reports.JasperReports.jasper_server: EXCEPTION: [Errno 111] Connection refused (111, 'Connection refused') 
2019-12-13 12:08:19,478 22035 ERROR demo1 odoo.addons.jasper_reports.JasperReports.jasper_server: EXCEPTION: [Errno 111] Connection refused (111, 'Connection refused') 
2019-12-13 12:08:20,480 22035 ERROR demo1 odoo.addons.jasper_reports.JasperReports.jasper_server: EXCEPTION: [Errno 111] Connection refused (111, 'Connection refused') 
2019-12-13 12:08:20,892 22035 INFO demo1 werkzeug: 127.0.0.1 - - [13/Dec/2019 12:08:20] "POST /longpolling/poll HTTP/1.1" 200 - 9 0.009 50.225
2019-12-13 12:08:21,482 22035 ERROR demo1 odoo.addons.jasper_reports.JasperReports.jasper_server: EXCEPTION: [Errno 111] Connection refused (111, 'Connection refused') 
2019-12-13 12:08:22,484 22035 ERROR demo1 odoo.addons.jasper_reports.JasperReports.jasper_server: EXCEPTION: [Errno 111] Connection refused (111, 'Connection refused') 
2019-12-13 12:08:23,486 22035 ERROR demo1 odoo.addons.jasper_reports.JasperReports.jasper_server: EXCEPTION: [Errno 111] Connection refused (111, 'Connection refused') 
2019-12-13 12:08:24,391 22035 INFO demo1 odoo.service.server: Initiating shutdown 
2019-12-13 12:08:24,392 22035 INFO demo1 odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-12-13 12:08:24,488 22035 ERROR demo1 odoo.addons.jasper_reports.JasperReports.jasper_server: EXCEPTION: [Errno 111] Connection refused (111, 'Connection refused')

**Comment by hiren-serpentcs** [comment] 2020-01-28 05:46
Hello @karthinr 

> Error: A JNI error has occurred, please check your installation and try again

Looking at your server log, it seems like the issue is with the java and jasper server compatibility.

Please check if you're able to run the JasperServer.

**Comment by Lourido** [comment] 2020-03-25 10:00
Hi hiren-serpentcs!

I'm here looking for a solution to the same issue reported by nopjeab:
Odoo 12 community on windows 10 gives me exactly the same error message "the server encountered an internal error ..." when I execute a Jasper Report on it.

It doesn't matter the report's content. I've tried with just one field or even without fields at all (just the label on the header) and the error message is the same.

Does it give you a clue?

**Comment by JayVora-SerpentCS** [comment] 2020-08-21 07:17
@hiren-serpentcs

**Comment by jellyfrank** [comment] 2020-09-02 07:17
I got same error when I export data to excel,  any solution?

**Comment by hiren-serpentcs** [comment] 2020-10-06 05:10
Hi @Lourido,

Can you please share the Odoo log and Jasper Server log (jasper_reports/java/jasperserver.log)

**Comment by croldan87** [comment] 2021-01-08 16:03
Hi, I have the same issue.
OS: Windows Server 2016
Odoo V12
It is a new installation

This is the log part for the jasper report (attached the complete log and odoo.conf)
[odoo.zip](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/5788129/odoo.zip)
[odoo.log](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/5788108/odoo.log)
:
2021-01-08 15:42:24,233 4232 INFO deka werkzeug: 127.0.0.1 - - [08/Jan/2021 15:42:24] "GET /web/image/res.partner/4605/image_small HTTP/1.1" 304 - 15 0.007 0.047
2021-01-08 15:42:26,616 4232 DEBUG ? odoo.service.server: cron1 polling for jobs 
2021-01-08 15:42:37,209 4232 DEBUG deka odoo.modules.registry: Multiprocess signaling check: [Registry - 31 -> 31] [Cache - 67 -> 67] 
2021-01-08 15:42:37,287 4232 INFO deka werkzeug: 127.0.0.1 - - [08/Jan/2021 15:42:37] "POST /web/action/load HTTP/1.1" 200 - 11 0.031 0.047
2021-01-08 15:42:37,371 4232 DEBUG deka odoo.modules.registry: Multiprocess signaling check: [Registry - 31 -> 31] [Cache - 67 -> 67] 
2021-01-08 15:42:37,440 4232 INFO deka odoo.addons.jasper_reports.JasperReports.jasper_report_config: Requested report: 'C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\jasper_reports\custom_reports\factura_deka.jrxml' 
2021-01-08 15:42:37,440 4232 INFO deka odoo.addons.jasper_reports.JasperReports.jasper_report_config: Temporary data file: 'C:\Windows\TEMP\tmplq0n4g5s' 
2021-01-08 15:42:41,616 4232 DEBUG deka odoo.modules.registry: Multiprocess signaling check: [Registry - 31 -> 31] [Cache - 67 -> 67] 
2021-01-08 15:42:41,679 4232 INFO deka odoo.addons.jasper_reports.JasperReports.jasper_report_config: Requested report: 'C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\jasper_reports\custom_reports\factura_deka.jrxml' 
2021-01-08 15:42:41,679 4232 INFO deka odoo.addons.jasper_reports.JasperReports.jasper_report_config: Temporary data file: 'C:\Windows\TEMP\tmp2cwrlofz' 
2021-01-08 15:42:45,870 4232 INFO ? werkzeug: 127.0.0.1 - - [08/Jan/2021 15:42:45] "GET /web/static/src/xml/dialog.xml?debug=1610120565826 HTTP/1.1" 200 - - - -
2021-01-08 15:42:48,657 4232 DEBUG ? odoo.service.server: cron0 polling for jobs 
2021-01-08 15:42:51,968 4232 INFO deka werkzeug: 127.0.0.1 - - [08/Jan/2021 15:42:51] "POST /longpolling/poll HTTP/1.1" 200 - 12 0.069 50.068
2021-01-08 15:43:03,498 4232 INFO deka werkzeug: 192.168.1.20 - - [08/Jan/2021 15:43:03] "POST /longpolling/poll HTTP/1.1" 200 - 9 0.031 50.032
2021-01-08 15:43:03,530 4232 DEBUG deka odoo.modules.registry: Multiprocess signaling check: [Registry - 31 -> 31] [Cache - 67 -> 67] 
2021-01-08 15:43:03,845 4232 INFO deka werkzeug: 127.0.0.1 - - [08/Jan/2021 15:43:03] "POST /longpolling/poll HTTP/1.1" 200 - 8 0.016 50.092
2021-01-08 15:43:03,867 4232 DEBUG deka odoo.modules.registry: Multiprocess signaling check: [Registry - 31 -> 31] [Cache - 67 -> 67]

**Comment by croldan87** [comment] 2021-01-19 07:34
Any fix for this? @JayVora-SerpentCS @hiren-serpentcs

**Comment by hiren-serpentcs** [comment] 2021-02-16 18:54
@croldan87 Are you Starting the Jasper Server separately?

**Comment by croldan87** [comment] 2021-02-16 21:15
@hiren-serpentcs no, I only do what I did in v11 and it didn't work. Just installed the module, create a template, create report, added to the reports and nothing else.

**Comment by rizagokay** [comment] 2021-03-25 13:21
> I got same error when I export data to excel, any solution?

@jellyhappy did you find any solution to this? We' re also experincing same problem during data export.

**Comment by Mohamed-Tarig** [comment] 2021-06-21 12:30
try to stop or uninstall Internet Download Manager if it installed

**Comment by croldan87** [comment] 2021-06-23 19:41
@Mohamed-Tarig it's not installed. This week I'll try with 13v, hope it works

**Comment by hiren-serpentcs** [comment] 2021-06-24 07:15
@rizagokay 

Please share your Java log (`jasper_reports/java/jasperserver.log`) it can help to debug the error.

**Comment by ibradin88** [comment] 2021-07-16 04:42
Same error for me
I use Odoo v.12, java version "1.8.0_281", OS Ubuntu 18.04.5 LTS. 
error details: 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/nantic/jasperreports/JasperServer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

~$ java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
~ $ sudo update-alternatives --config java
There is only one alternative in link group java (providing /usr/bin/java): /usr/local/java/jdk1.8.0_281/bin/java
Nothing to configure.

Log Server :
2021-07-16 04:33:28,207 2975 INFO demo12 werkzeug: 103.127.65.150 - - [16/Jul/2021 04:33:28] "POST /web/dataset/call_kw/stock.picking/read HTTP/1.1" 200 - 90 0.503 0.0292021-07-16 04:33:28,330 2975 INFO demo12 werkzeug: 103.127.65.150 - - [16/Jul/2021 04:33:28] "POST /web/dataset/call_kw/stock.move/read HTTP/1.1" 200 - 49 0.068 0.022
2021-07-16 04:33:28,451 2975 INFO demo12 werkzeug: 103.127.65.150 - - [16/Jul/2021 04:33:28] "POST /mail/read_followers HTTP/1.1" 200 - 7 0.005 0.005
2021-07-16 04:33:28,479 2975 INFO demo12 werkzeug: 103.127.65.150 - - [16/Jul/2021 04:33:28] "GET /web/image/res.partner/2/image_small HTTP/1.1" 200 - 15 0.003 0.007
2021-07-16 04:33:28,501 2975 INFO demo12 werkzeug: 103.127.65.150 - - [16/Jul/2021 04:33:28] "POST /web/dataset/call_kw/mail.message/message_format HTTP/1.1" 200 - 30 0.045 0.015
2021-07-16 04:33:39,712 2975 INFO demo12 werkzeug: 103.127.65.150 - - [16/Jul/2021 04:33:39] "POST /web/dataset/call_button HTTP/1.1" 200 - 2 0.001 0.002
2021-07-16 04:33:39,753 2975 INFO ? werkzeug: 103.127.65.150 - - [16/Jul/2021 04:33:39] "GET /web/static/src/img/spin.png HTTP/1.1" 200 - - - -
2021-07-16 04:33:39,777 2975 INFO demo12 odoo.addons.jasper_reports.JasperReports.jasper_report_config: Requested report: '/opt/odoo/addons_custom/surat_jalan/report/report_surat_jalan.jrxml' 
2021-07-16 04:33:39,790 2975 INFO demo12 odoo.addons.jasper_reports.JasperReports.jasper_report_config: Temporary data file: '/tmp/tmp8b61tloz' 
2021-07-16 04:33:39,946 2975 INFO ? werkzeug: 103.127.65.150 - - [16/Jul/2021 04:33:39] "GET /web/static/src/xml/dialog.xml HTTP/1.1" 200 - - - -

**Another issue: size of resulting PDF (jasper) file is 0 bytes (blank)**
warning:  "We can't open this file. Something went wrong."

can anyone help me? @JayVora-SerpentCS @hiren-serpentcs
Thanks

**Comment by MiguelJimenez1998** [comment] 2022-03-07 05:07
Hi

I solve this problem, add in my `nginx.conf` this line `large_client_header_buffers 4 128k;` 

Hope it helps

**Closed as completed** 2022-03-07 12:02 UTC
Labels: Need information, v12.0

**Comment by antonycatalist** [comment] 2024-09-30 06:41
Something happened while trying to contact the server, check that the server is online and that you still have a working network connection.
![Screenshot 2024-09-30 120957](https://github.com/user-attachments/assets/d71efd15-961f-4618-a1fd-a01fdb4fb201)
This issue is coming, tried all the above scenarios. Please support
