### ISSUE TITLE
Error while printing demo report

### ISSUE THREAD

**Issue by chinu1994** [JayVora-SerpentCS/Jasperv8#92] opened 2019-08-08 07:36 UTC
odoo.exceptions.UserError: ("Report Error\n<Fault 0: 'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: Metaspace'>", '') - - -

This is in odoo12 with java version 11

**Comment by JayVora-SerpentCS** [comment] 2019-08-08 11:14
@hiren-serpentcs

**Comment by hiren-serpentcs** [comment] 2019-08-08 11:24
Hello @chinu1994,

Thanks for reporting the issue. Can you please make sure that you have the latest pull of the 12.0 branch from [here](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/tree/12.0). 
If you already have the latest pull, can you please describe the steps to reproduce the same?

Thanks

**Comment by alang0808** [comment] 2019-08-19 01:10
I encountered the same issue with latest version 12 with java 12, could you please kindly review?


JasperServer: Filling report...
JasperServer: Exporting...
2019-08-19 01:07:21,293 7896 ERROR Adoo12 odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "d:\odoo12.0\odoo\extra-addons\jasper_reports\JasperReports\jasper_server.py", line 113, in execute
    return self.proxy.Report.execute(*args)
  File "C:\Users\17991\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\17991\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1452, in __request
    verbose=self.__verbose
  File "C:\Users\17991\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Users\17991\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "C:\Users\17991\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1342, in parse_response
    return u.close()
  File "C:\Users\17991\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 0: 'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: java.io.IOException: The byte array is not a recognized imageformat.'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\odoo12.0\odoo\odoo\addons\base\models\ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "D:\odoo12.0\odoo\odoo\http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "D:\odoo12.0\odoo\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo12.0\odoo\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo12.0\odoo\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo12.0\odoo\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "D:\odoo12.0\odoo\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo12.0\odoo\extra-addons\jasper_reports\controllers\main.py", line 58, in report_routes
    context).render_jasper(docids, data=data)
  File "d:\odoo12.0\odoo\extra-addons\jasper_reports\models\report_xml.py", line 177, in render_jasper
    jasper = r.execute()
  File "d:\odoo12.0\odoo\extra-addons\jasper_reports\JasperReports\jasper_report_config.py", line 177, in execute
    data_file, output_file, sub_report_data_files)
  File "d:\odoo12.0\odoo\extra-addons\jasper_reports\JasperReports\jasper_report_config.py", line 263, in execute_report
    connection_parameters, self.report_path, output_file, parameters)
  File "d:\odoo12.0\odoo\extra-addons\jasper_reports\JasperReports\jasper_server.py", line 126, in execute
    raise UserError(_('Report Error\n%s') % e)
odoo.exceptions.UserError: ("Report Error\n<Fault 0: 'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: java.io.IOException: The byte array is not a recognized imageformat.'>", '')

**Comment by hiren-serpentcs** [comment] 2019-08-28 06:02
@alang0808,
It's due to Image into your `.jrxml` file which the Jasper Server is not able to recognize. 

Will you please try change or remove the Image and print again?

**Comment by alang0808** [comment] 2019-08-29 06:37
@hiren-serpentcs Hello, thanks for your reply, l tried to remove the image it works, and if put the image with local path it works as well, but if keep image source("http://serpentcs.com/logo.png") as your default template report, it raises the issue above, the internet connection is OK as I tried success by browser directly, does it mean it doesn't work for for this kind of url?
Any solution for this kind of url image? Please kindly advise, thanks.

**Comment by hiren-serpentcs** [comment] 2020-10-06 05:12
Hi @alang0808 

Yes, it works with the URL but due to the security reasons, it might not be able to fetch the image from URL. Better to upload the image on the `.jrxml` itself.

**Comment by hiren-serpentcs** [comment] 2021-10-06 05:57
Closing as no updates.

**Closed as completed by hiren-serpentcs** 2021-10-06 05:57 UTC

**Comment by mohamed-itk** [comment] 2022-02-02 15:14
Hello i ran into the same issue with odoo 14
