### ISSUE TITLE
Can't add line items in report

### ISSUE THREAD

**Issue by arun143jacob** [JayVora-SerpentCS/Jasperv8#83] opened 2019-03-28 07:00 UTC
[Jasper Sales Report (46).pdf](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/3016568/Jasper.Sales.Report.46.pdf)
I can't add line items in Jasper report.
I checked with the sample file sale_order_report.jrxml.
But, only the first line appears in the report.

**Comment by hiren-serpentcs** [comment] 2019-04-05 09:17
Hello @arun143jacob ,

Thanks for Reporting Issue.

This might be because of the design of the your Jasper report.
Can you please provide us your `.jrml` file so we can check if it is because of our module or not ?

Meanwhile, you can check detailed configuration in https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation#creating-jasper-report-with-relation-fields

**Comment by arun143jacob** [comment] 2019-04-05 09:25
Hi,

I can't share .jrml file in GitHub.

I attached the file with this mail.

PFA

Thanks & Regards
Arun Jacob

**Comment by hiren-serpentcs** [comment] 2019-04-05 09:52
Hi @arun143jacob 

We are not able to find any attachment.

**Comment by arun143jacob** [comment] 2019-04-05 09:57
[sale_order_report.txt](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/3047347/sale_order_report.txt)

Just rename the text file as .jrml file and check.

**Comment by hiren-serpentcs** [comment] 2019-07-16 09:34
Hello @arun143jacob,

The issue is with Jasper Studio's version compatibility. The newer version on Jasper Studio does not work with the `printRepeatedValue` feature.

You can fix the issue by downgrading the Jasper Studio Version compatibility as shown here: [Documentation](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation#53-solves-the-uuid-error-by-updating-the-libraries)

**Comment by hiren-serpentcs** [comment] 2020-08-20 07:15
@JayVora-SerpentCS 

We can assume this is fixed and close the issue.

@arun143jacob  you can reopen the issue if it's not fixed.

**Closed as completed** 2020-08-21 07:14 UTC
